[platformio]
workspace_dir = ../../../.pio-workspaces/Avi_ESP_Libs/platformio_espidf

[env:esp32-s3-devkitc-1]
platform = espressif32@7.0.1
board = esp32-s3-devkitc-1
framework = espidf
lib_deps = symlink://../..
build_flags = -std=gnu++17
