name: Update Workflows

on:
  repository_dispatch:
    types: [repository]

jobs:
  add-dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Add Repository Dispatch
      run: |
        echo -e '\n      - name: Repository Dispatch1' >> .github/workflows/main.yml
        echo '        uses: peter-evans/repository-dispatch@v2' >> .github/workflows/main.yml
        echo '        with:' >> .github/workflows/main.yml
        echo '          token: ${{ '${{ secrets.REPO_GITHUB_TOKEN }}' }}' >> .github/workflows/main.yml
        echo '          repository: ${{ github.event.client_payload.repo }}' >> .github/workflows/main.yml
        echo '          event-type: update' >> .github/workflows/main.yml
        echo ;

    - name: Create pull request
      uses: peter-evans/create-pull-request@v4
      with:
        title: Update main.yml
        commit-message: Update main.yml
        branch: update-main-yml
        branch-suffix: timestamp
        delete-branch: true
        base: main
        labels: automated
        body: |
          This is an automated update to the main.yml file. Add a new repository.
        token: ${{ secrets.REPO_GITHUB_TOKEN }}